= {lab_name}

Welcome to the Red Hat OpenStack Services on OpenShift (RHOSO) lab instructions.
These instructions will guide you through the installation of the next generation of Red Hat's OpenStack product onto an existing OpenShift Cluster utilizing a bastion host and a single host for the data plane.

In this lab, you will use the following infrastructure:

* A 3 OCP controller + 3 OCP workers nodes 4.15 OCP cluster
* A bastion host to access to the OCP environment
* A RHEL 9.4 virtualised compute host

In this lab, you will cover the following topics:

* xref:prereqs-argocd.adoc[Perform Prerequisite Operations]
* xref:prereqs.adoc[Install the Operators prerequisites using OpenShift gitops]
* xref:install-operators.adoc[Install the Red Hat OpenStack Platform Service Operators using OpenShift gitops]
* xref:network-isolation.adoc[Prepare OCP for OpenStack Network Isolation using OpenShift gitops]
* xref:deploy-rhoso.adoc[Deploy RHOSO using OpenShift gitops]
* xref:access.adoc[Access OpenStack]
* xref:scale-out.adoc[Scale Out your deployment using Cluster Baremetal Operator provisioned nodes]

Within the lab environment, you will be able to copy and paste the specified commands into the CLI.
For some steps you may also need to edit some of the commands from the  instructions.

*Be sure to review all commands carefully both for functionality and syntax!*
